[build]
  command = "npm run build:frontend"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://serviceswebsite-2.onrender.com"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://serviceswebsite-2.onrender.com"
